language: rust

dist: xenial

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev

script:
  - cargo build
  - cargo build --features v3_7_0
